### PR TITLE
Adding profiling support to client logger

### PR DESCRIPTION
**Pull request by AGresvig**
Ref https://github.com/plyo/plyo.db/pull/419

### CODE REVIEW

**Review by jifeon — APPROVED** [review]

**Comment by AGresvig** [comment]
@jifeon finally got around to trying this out client side. Example:

```
  /**
   * The first progressive action
   */
  onPreviewLoad = () => {
    // Prepare a new image instance for canvas with CORS enabled
    // If skip this step for some unknown reason the canvas becomes tainted and starts throwing a SecurityError
    // https://developer.mozilla.org/en/docs/Web/HTML/CORS_enabled_image
    const { preview } = this;
    logger.profile('Time to load preview for image ' + preview.src);
    const image = new Image();
    this.thumbnail = image;
    image.crossOrigin = preview.crossOrigin;
    image.onload = this.onPreviewReady;
    image.src = preview.src;

    // Make sure the load event fires for cached preview too
    if (image.complete) {
      logger.profile('Time to load preview for image ' + preview.src);
      this.onPreviewReady();
    }
  };
```
Spits out:

image


Seems to work well client-side also now. What do you think?

**Comment by jifeon** [comment]
But we agreed to use `timer` approach since we need to measure async operations. We can't use `profile` with same labels - it's only for sync operations.

**Comment by jifeon** [comment]
@apsavin @AGresvig pls take a look, I think it's ready to merge

**Comment by jifeon** [comment]
[Log time-consuming operations for performance verification purposes](https://trello.com/c/NugxodEF/1080-log-time-consuming-operations-for-performance-verification-purposes)

**Review by AGresvig — COMMENTED** [review]
Great! Thanks so much

**Review by AGresvig — COMMENTED** [review]
👍

**Pull request merged**
