### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by jifeon**
for review @AGresvig @frenzzy

### CODE REVIEW

**Comment by AGresvig** [comment]
LGTM!
Hos is it used? I mean, how can we access dot-files when this is used as a dependency, not forked?

**Comment by jifeon** [comment]
Not sure I understand you 100% but like for [logger](https://github.com/plyo/logger) we have `postinstall` script in `package.json`, files inside `lib` are compiled into `dist` folder when you do `npm install`.

**Comment by jifeon** [comment]
Why we need to access dot-files?

**Comment by AGresvig** [comment]
> Why we need to access dot-files?

I mean, how do we use `.babelrc` from this dep. for example

**Comment by AGresvig** [comment]
> files inside lib are compiled into dist folder when you do npm install

Makes sense, thanks

**Comment by jifeon** [comment]
> I mean, how do we use .babelrc from this dep. for example

The answer is we shouldn't, these files are for this repo, for development and build purposes. The only thing we can use from this repo is files from `lib` directory.

**Comment by AGresvig** [comment]
Oh I see thanks for clarifying

**Pull request merged**
