### PR TITLE
PP-3782 [CP] Field 'Percent owned' displays as fractional number

### PR DESCRIPTION
**Pull request by ZhuravlevaS**
fix export

### CODE REVIEW

**Review by frenzzy — APPROVED** [review]

**Comment by frenzzy** [comment]
Published as plyo-tools@4.2.1

**Comment by jifeon** [comment]
@frenzzy it actually looks like breaking change (major version) :)

**Comment by frenzzy** [comment]
nope, it is a patch for the previous version (see https://github.com/plyo/plyo.tools/pull/22) where was a breaking change to undo the breaking change :)

**Comment by jifeon** [comment]
👍

**Pull request merged**
